### ISSUE TITLE
Features Request: Mark All Read

### ISSUE THREAD

**Issue by HonestAbe7** [rh-id/a-news-provider#14]
Please consider adding an option to mark all read in the RSS feeds.

**Comment by rh-id** [comment]
I dont see any compelling reason to add "mark all as read" because when new RSS list was provided by the source old RSS will be removed.

**Comment by HonestAbe7** [comment]
I didn't know they automatically are deleted. If I see new bold RSS feeds I will just long press to make them read for now.

**Comment by rh-id** [comment]
Mark as read doesn't automatically delete RSS. And doesn't related with the feature request that you want. If you think you have encounter a bug then log a new issue and explain it properly with step by step of how you encounter the issue because As both user and a developer I really can't understand what you are trying to describe and explain.

**Comment by rh-id** [comment]
And as per what I stated there is no compelling reason, and you are not providing more reason of why the feature should be added. I will close this issue

**Comment by HonestAbe7** [comment]
Well, if someone does have lots of items in a feed, it just would take more time to mark them all read. I will just hold down on my phone in the app until all are unread.
